name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Build
        run: npx nypm@latest run dev:prepare

      - name: Git config
        run: |
          git config --global user.name 'ReleaseBot'
          git config --global user.email 'ghbot@onecode.no'

      - name: Release
        run: npx nypm@latest run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NUXT_REDIS_URL: "redis://localhost:${{ job.services.redis.ports['6379'] }}"
