name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Build
        run: npx nypm@latest build

      - name: Release
        run: npx nypm@latest run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
